//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TresEnRayaConsola {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TresEnRayaConsola.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenidos .
        /// </summary>
        internal static string Bienvenida {
            get {
                return ResourceManager.GetString("Bienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La casilla .
        /// </summary>
        internal static string Casilla {
            get {
                return ResourceManager.GetString("Casilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador que comienza el juego es .
        /// </summary>
        internal static string Comienza {
            get {
                return ResourceManager.GetString("Comienza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las dimensiones del tablero son.
        /// </summary>
        internal static string Dimensiones {
            get {
                return ResourceManager.GetString("Dimensiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , elija la columna de la casilla:.
        /// </summary>
        internal static string ElegirColumna {
            get {
                return ResourceManager.GetString("ElegirColumna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , elija la fila de la casilla:.
        /// </summary>
        internal static string ElegirFila {
            get {
                return ResourceManager.GetString("ElegirFila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  escoja la ficha que usará .
        /// </summary>
        internal static string EscogerFicha {
            get {
                return ResourceManager.GetString("EscogerFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es una de sus fichas..
        /// </summary>
        internal static string FichaIncorrecta {
            get {
                return ResourceManager.GetString("FichaIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  no está dentro del tablero, por favor elija otra: .
        /// </summary>
        internal static string FueraTablero {
            get {
                return ResourceManager.GetString("FueraTablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  es el ganador!!!.
        /// </summary>
        internal static string Ganador {
            get {
                return ResourceManager.GetString("Ganador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador.
        /// </summary>
        internal static string Jugador {
            get {
                return ResourceManager.GetString("Jugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida acabó en empate..
        /// </summary>
        internal static string NoGanador {
            get {
                return ResourceManager.GetString("NoGanador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca solo números..
        /// </summary>
        internal static string NoLetra {
            get {
                return ResourceManager.GetString("NoLetra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta es la forma en la que se debe escribir la posición para elegirla:.
        /// </summary>
        internal static string NombrarPosiciones {
            get {
                return ResourceManager.GetString("NombrarPosiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , introduzca su nombre:.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca el número de jugadores.
        /// </summary>
        internal static string NumeroJugadores {
            get {
                return ResourceManager.GetString("NumeroJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor Jugador .
        /// </summary>
        internal static string PedirJugador {
            get {
                return ResourceManager.GetString("PedirJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba el símbolo de las fichas con las que quiere jugar (escriba una coma para separar los símbolos):.
        /// </summary>
        internal static string PedirSimbolo {
            get {
                return ResourceManager.GetString("PedirSimbolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  está ocupada, por favor elija otra: .
        /// </summary>
        internal static string PosicionOcupada {
            get {
                return ResourceManager.GetString("PosicionOcupada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tablero lleno..
        /// </summary>
        internal static string TableroLleno {
            get {
                return ResourceManager.GetString("TableroLleno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  y .
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
    }
}
